config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get    'unlock_account'       => 'users#unlock_account'

  # Dynamic error pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # devise_for :users
  # Static pages
  root                      'static_pages#home'
  # get    'terms'         => 'static_pages#terms'
  # get	   'privacy'       => 'static_pages#privacy'
  # get    'about'         => 'static_pages#about'
  # get    'apps'          => 'static_pages#apps'
  # get    'changelog'     => 'static_pages#changelog'
  # get    'feedback'      => 'static_pages#feedback'
  get    'support'       => 'static_pages#support'

  # Sessions
  get	   'login'		     => 'sessions#new'
  post	 'login'		     => 'sessions#create'
  delete 'logout'	       => 'sessions#destroy'

  # Users
  # get    'profile'       => 'users#show'
  get    'signup'        => 'users#new'
  
  resources :users, only: [:new, :show, :create, :edit, :update, :destroy]
  
  # Destroy
  get  'users/:id/remove_all_books' => 'users#remove_all_books', as: :remove_all_books
  get  'users/:id/remove_all_classbooks' => 'users#remove_all_classbooks', as: :remove_all_classbooks
  get  'users/:id/remove_all_lists' => 'users#remove_all_lists', as: :remove_all_lists
  
  # Lists
  get    'import_page'        => 'lists#import_page'
  
  resources :lists
  
  # Books
  get    'search'        => 'books#search'
  
  resources :books
  resources :reviews, only: [:edit, :update]

  # Password Resets
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/new'
  get 'password_resets/edit'

  # Classrooms
  get    'classroom_join'      => 'classrooms#join'
  get    'classroom_activity'  => 'classrooms#activity'
  get    'student'             => 'classrooms#student'
  get    'leaderboards'        => 'classrooms#leaderboards'
  get    'students'            => 'classrooms#students'
  get    'archived'            => 'classrooms#archived'
  get    'info'                => 'classrooms#info'
  get    'leave_classroom'     => 'classrooms#leave'
  
  get  'classrooms/:id/remove' => 'classrooms#remove_student', as: :remove_student
  get  'classrooms/:id/remove_self' => 'classrooms#remove_self', as: :remove_self
  get  'classrooms/:id/archive' => 'classrooms#archive', as: :archive
  
  resources :classrooms
  resources :terms
  
  # Classbooks
  get    'classroomsearch'     => 'classbooks#search'
  get    'classbooks_print'    => 'classbooks#print'
  resources :classbooks
  
end

app/models/list.rb
class List < ActiveRecord::Base
  # require 'csv'
  
  # Default scope
  default_scope -> { order(created_at: :asc)}
  
  # Associations
  belongs_to :user
  has_many :books
  
  # Callbacks
  before_destroy :destroy_children

  # Validations
  validates :user_id, presence: true # Lists must belong to a user.
  validates :title, presence: true, length: { maximum: 50 } # There must be a title
  
  private
    def destroy_children
			Book.where(list_id: self.id).each do |book|
				book.destroy
			end
		end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	# before_action :authenticate_user!
	before_action :logged_in_user
	before_action :get_user
	before_action :correct_user,   only: [:show, :destroy, :edit, :update]
	before_action :get_list, only: [:edit, :update, :show]
	before_action :redirect_to_classrooms_if_no_books
	# before_action :redirect, only: [:update]

	def new
		@list = current_user.lists.build if logged_in?
	end

	def create
		@list = current_user.lists.build(list_params)
		if @list.save
			flash[:success] = "Your new list, "+ @list.title + ", was created."
			redirect_to list_path(@list)
		else
			render 'new'
		end
	end

	def update
	    if @list.update_attributes(list_params)
	      flash[:success] = "Your changes to "+ @list.title + " were saved."
	    	redirect_to edit_list_path(@list)
	    else
	    	render 'edit'
	    end
	end

	def show
		# Calculate total params
		@total_pages = total_pages(@list.books)
	end

	def destroy
		redirect_to lists_path
		flash[:success] = "Your list was deleted."
		@list.destroy
	end

	private
		
		def list_params
			params.require(:list).permit(:title, :user_id, :goodreads)
		end
		
		def get_user
			@user = current_user
		end

		def get_list
			@list = current_user.lists.find(params[:id])
		end

		def correct_user
			@list = current_user.lists.find_by(id: params[:id])
			if @list.nil?
				redirect_to lists_path
			end
		end
		
		def redirect_to_classrooms_if_no_books
			unless current_user.lists_enabled
				redirect_to classrooms_path
			end
		end
		
		# def redirect
		# 	redirect_to root_url
		# end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_list.html.erb
<%= link_to list_path(list) do %>
	<div class="col-sm-6 col-md-4">
		<div class="classroom-box">
			<p><strong><%= list.title %></h4></strong></p>
			<span><%= pluralize(list.books.size, "book") %></span>
		</div>
	</div>
<% end %>

app/views/lists/_sidebar.html.erb
<% content_for(:side_bar) do %>
	<div class="sidebar-group">
		<li>
			<%= link_to new_list_path do %>
				<i class="fa fa-plus"></i>
				<span>New List</span>
			<% end %>
		</li>
		<li>
			<%= link_to lists_path do %>
				<i class="fa fa-list"></i>
				<span>My Lists</span>
			<% end %>
		</li>
	</div>
<% end %>

app/views/lists/_sidebar_indv_list.html.erb
<% content_for(:side_bar) do %>
    <% if @list %>
        <div class="sidebar-group">
            <li>
                <h3 id="title">
                    <%= @list.title %>
                </h3>
            </li>
        </div>
        <div class="sidebar-group">
            <li>
                <p class="sidebar-group-title">Add Book</p>
            </li>
            <li>
                <%= link_to search_path(list_id: @list.id) do %>
                <i class="fa fa-search"></i>
                <span>Search</span>
                <% end %>
            </li>
            <li>
                <%= link_to new_book_path(list_id: @list.id) do %>
                    <i class="fa fa-plus"></i>
                    <span>Manually</span>
                <% end %>
            </li>
        </div>
        <div class="sidebar-group">
            <li>
                <p class="sidebar-group-title">My List</p>
            </li>
            <li>
                <%= link_to list_path(@list) do %>
                <i class="fa fa-book"></i>
                <span>My Books</span>
                <% end %>
            </li>
            <li>
                <%= link_to(edit_list_path(@list)) do %>
                <i class="fa fa-edit"></i>
                <span>Change List Name</span>
                <% end %>
            </li>
            <li>
                <%= link_to(@list, method: :delete, data: {confirm: "Are you sure you want to delete this list? All of its books will be deleted. This action cannot be undone."}) do %>
                <i class="fa fa-trash"></i>
                <span>Delete List</span>
                <% end %>
            </li>
        </div>
        <div class="sidebar-group">
            <li>
                <p class="sidebar-group-title">Info</p>
            </li>
            <li><a>Created: <%= @list.created_at.strftime("%m/%d/%Y") %></a></li>
            <li><a>Total books: <%= @list.books.count %></a></li>
            <% if @total_pages %>
            	<li><a>Total pages: <%= @total_pages %></a></li>
            <% end %>
        </div>
    <% end %>
<% end %>

app/views/lists/edit.html.erb
<% provide(:title, "Change this list's name") %>
<%= render "lists/sidebar_indv_list" %>
<div class="container-flui">
  <h1 class="h1-default">Change name</h1>
    <%= form_for(@list) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Give your list a name" %>

      <div class="center bottom-medium-margins">
        <%= f.submit "Save changes", class: "btn btn-default green-hover" %>
      </div>
    <% end %>
</div>

app/views/lists/import_page.html.erb
<% provide(:title, 'Import books from Goodreads') %>
<div class="container-fluid">
    <p style="margin-top:30px"><%= link_to "< Back to your lists", lists_path %></p>
    <div class="col-md-6 col-md-offset-3">
        <h1 id="import-title">Import books from Goodreads</h1>
        <p id="import-text">If you have a .csv file from Goodreads, you can import those books here. Information on importing can be found in our <%= link_to "FAQs", faq_path %>.<br></p>    
        <%= form_tag import_lists_path, multipart: true, id: "import-form" do %>
            <%= file_field_tag :file, class: "form-control" %>
            <%# hidden_field_tag 'id', params[:id] %>
            <div class="center">
                <%= submit_tag "Import CSV", class: "btn btn-default" %>
            </div>
        <% end %>
    </div>
</div>

<script>

// Change title and text when the import starts
var $importForm = $("#import-form");
$importForm.submit(function(){
    $('#import-title').html('Importing...');
    $('#import-text').html('This can take a while if you have a large library. Keep this tab open.');
    
});

</script>

app/views/lists/index.html.erb
<% provide(:title, "Your Lists") %>
<%= render "lists/sidebar" %>

<div class="container-fluid">

	<div class="row" style="margin-top: 30px; margin-bottom: 30px">
		<div class="col-xs-6" style="margin-left:0px">
			<h1 class="sm-center pull-left">My lists</h1>
		</div>
		<div class="col-xs-6 center">
			<div class="pull-right"> 
				<% unless @user.lists.count == 0 %>
					<%= link_to "Add a book", search_path, class: "btn btn-default" %>
				<% else %>
					<%= link_to "New list", new_list_path, class: "btn btn-default" %>
				<% end %>
			</div>
		</div>
	</div>
	
	<% if current_user.books.count == 0 && current_user.lists.count > 0%>
		<p style="color: gray">
			<span class="glyphicon glyphicon-info-sign"></span>	
			Tip: Lists are different than classrooms. They're personal collections of books for only you to see.
		</p>
	<% end %>
	
	<% unless @user.lists.count == 0 %>
		<div class="row row-centered-mobile">
			<div class="row">
				<%= render @user.lists %>
			</div>
		</div>
	<% else %>
		<div class="center">
			<%= image_tag 'book.png', class: "list-empty-state-image" %>
			<h3 class="classroom-empty-state-main-heading">You don't have any lists.</h3>
			<p class="classroom-empty-state-subtext">Once you create a list, it'll appear here.</p>
			   
		</div>
	<% end %>
</div>

app/views/lists/new.html.erb
<% provide(:title, 'Create a new list') %>
<%= render "lists/sidebar" %>

<div class="container-fluid">
	<h1 class="h1-default">Create a new list</h4>
	<%= form_for(@list) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.text_field :title, class: 'form-control', placeholder: 'Give your list a name (50 characters max)', autofocus: 'autofocus' %>
		<%= f.submit "Create list", class: "btn btn-default" %>
	<% end %>
</div>

<script>
	// Disable form after one click so that you can't add the book twice
  var $myForm = $("#new_list");
	$myForm.submit(function(){
	    $myForm.submit(function(){
	        return false;
	    });
	});

</script>

app/views/lists/show.html.erb
<% provide(:title, @list.title) %>
<%= render "lists/sidebar_indv_list" %>

<div class="container-fluid">
	<h1 class="h1-default">My books</h1>
  <!-- Render books -->
  <% if @list.books.any? %>
    <div class="row">
      <%= render @list.books %>
    </div>
  <% else %>
    <p>There are no books in the list <strong><%= @list.title %></strong>. Why don't you add one right now?</p>
  <% end %>
</div>