config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get    'unlock_account'       => 'users#unlock_account'

  # Dynamic error pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # devise_for :users
  # Static pages
  root                      'static_pages#home'
  # get    'terms'         => 'static_pages#terms'
  # get	   'privacy'       => 'static_pages#privacy'
  # get    'about'         => 'static_pages#about'
  # get    'apps'          => 'static_pages#apps'
  # get    'changelog'     => 'static_pages#changelog'
  # get    'feedback'      => 'static_pages#feedback'
  get    'support'       => 'static_pages#support'

  # Sessions
  get	   'login'		     => 'sessions#new'
  post	 'login'		     => 'sessions#create'
  delete 'logout'	       => 'sessions#destroy'

  # Users
  # get    'profile'       => 'users#show'
  get    'signup'        => 'users#new'
  
  resources :users, only: [:new, :show, :create, :edit, :update, :destroy]
  
  # Destroy
  get  'users/:id/remove_all_books' => 'users#remove_all_books', as: :remove_all_books
  get  'users/:id/remove_all_classbooks' => 'users#remove_all_classbooks', as: :remove_all_classbooks
  get  'users/:id/remove_all_lists' => 'users#remove_all_lists', as: :remove_all_lists
  
  # Lists
  get    'import_page'        => 'lists#import_page'
  
  resources :lists
  
  # Books
  get    'search'        => 'books#search'
  
  resources :books
  resources :reviews, only: [:edit, :update]

  # Password Resets
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/new'
  get 'password_resets/edit'

  # Classrooms
  get    'classroom_join'      => 'classrooms#join'
  get    'classroom_activity'  => 'classrooms#activity'
  get    'student'             => 'classrooms#student'
  get    'leaderboards'        => 'classrooms#leaderboards'
  get    'students'            => 'classrooms#students'
  get    'archived'            => 'classrooms#archived'
  get    'info'                => 'classrooms#info'
  get    'leave_classroom'     => 'classrooms#leave'
  
  get  'classrooms/:id/remove' => 'classrooms#remove_student', as: :remove_student
  get  'classrooms/:id/remove_self' => 'classrooms#remove_self', as: :remove_self
  get  'classrooms/:id/archive' => 'classrooms#archive', as: :archive
  
  resources :classrooms
  resources :terms
  
  # Classbooks
  get    'classroomsearch'     => 'classbooks#search'
  get    'classbooks_print'    => 'classbooks#print'
  resources :classbooks
  
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :classroom_teachers
	has_many :classroom_students
	has_many :teaching_classrooms, through: :classroom_teachers
	has_many :attending_classrooms, through: :classroom_students
  
	has_many :lists, dependent: :destroy
	has_many :books, through: :lists, dependent: :destroy
	has_many :classbooks
	has_many :reviews
	
	default_scope -> { order(created_at: :asc)}

	attr_accessor :remember_token, :reset_token
	
	# Callbacks
	before_save { email.downcase! }
	# after_save :init
	
	# Make sure name exists and is less than 50
	validates :name,  presence: true, length: { maximum: 50 }

	# VALID_USERNAME_REGEX = /\A\S\w*$\z/
 	# 	validates :username,  length: { maximum: 50 }, uniqueness: { case_sensitive: false }, format: { with: VALID_USERNAME_REGEX }, allow_nil: true

 	# Set Email format with REGEX
 	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 	# Make sure email exists, is less than 255, fits VALID_EMAIL_REGEX, and is unique
 	validates :email, presence: true, length: { maximum: 255 },
                	  format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	has_secure_password
	# Make sure the password has a minimum length
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	# validates :bio,  length: { maximum: 140 }, obscenity: { sanitize: true, replacement: :vowels }
	mount_uploader :avatar, AvatarUploader
	validate :avatar_size

	# Returns the hash digest of the given string.
	def User.digest(string)
  	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
  	BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token.
	def User.new_token
  	SecureRandom.urlsafe_base64
	end

	# Remembers a user in the database for use in persistent sessions.
	def remember
  	self.remember_token = User.new_token
  	update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Returns true if the given token matches the digest.
	def authenticated?(attribute, token)
	  digest = send("#{attribute}_digest")
	  return false if digest.nil?
	  BCrypt::Password.new(digest).is_password?(token)
	end

	# Forgets a user.
	def forget
  	update_attribute(:remember_digest, nil)
	end

	#PASSWORD RESET
	def create_reset_digest
  	self.reset_token = User.new_token
  	update_attribute(:reset_digest, User.digest(reset_token))
  	update_attribute(:reset_sent_at, Time.zone.now)
	end

	def send_password_reset_email
  	UserMailer.password_reset(self).deliver_now
	end

	# Returns true if a password reset has expired.
	def password_reset_expired?
  	reset_sent_at < 2.hours.ago
	end
	
	def has_badge?(badge)
		has_badge = false
		self.badges.each do |temp_badge|
			if temp_badge.id == badge.id
				has_badge = true
			end
		end
		return has_badge
	end
	
	def classrooms(attributes="")
		unless attributes.empty?
			return attending_classrooms.select(attributes) + teaching_classrooms.select(attributes)
		else 
			return attending_classrooms + teaching_classrooms
		end
	end
	
  private
	def init
		# Create 3 preset lists when a user signs up.
      self.lists.create(title: "Already Read")
      self.lists.create(title: "Want to Read")
      self.lists.create(title: "Favorites")
	end
		
  	# Validates the size of an uploaded picture.
  	def avatar_size
    	if avatar.size > 5.megabytes
      		errors.add(:avatar, "should be less than 5MB")
    	end
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!, only: [:edit, :update, :admin, :show, :explore]
  before_action :logged_in_change_links, only: [:new]
  before_action :logged_in_user, only: [:edit, :update, :admin]
  before_action :correct_user,   only: [:edit, :update]
  # before_action :profile_private, only: [:show]
  before_action :filter_admin, only: [:admin]
  before_action :authenticate, only: [:admin]
  before_action :check_if_user_exists, only: [:pedit]
  
  def unlock_account
    if params[:email]
      @user = User.find_by(email: params[:email])
      if @user
        log_in @user
        redirect_to pedit_path
        flash.now[:success] = "We found your account."
      else
        flash.now[:danger] = "Couldn't find a user with that email. Check if there are typos."
      end
    end
  end
	
	def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      # Create 3 preset lists when a user signs up.
      @user.lists.create(title: "Already Read")
      @user.lists.create(title: "Want to Read")
      @user.lists.create(title: "Favorites")
      redirect_to classrooms_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])

    @user_classbooks = @user.classbooks.select("classbooks.id, classbooks.image_url, classbooks.manual, classbooks.title, classbooks.author, classbooks.pages, classbooks.created_at").limit(10)
    @user_books = @user.books.select("books.id, books.image_url, books.manual, books.title, books.author, books.pages, books.created_at").limit(10)
    @recent_books = (@user_classbooks + @user_books).sort_by &:created_at
    @books_count =  @user.classbooks.count + @user.books.count
    @page_count = @user.classbooks.sum(:pages) + @user.books.sum(:pages)
    
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your settings were saved."
      redirect_to edit_user_path(@user)
    else
      flash.now[:danger] = "An error occurred with your submission."
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    
    # Destroy all of the user's lists
    @user.lists.each do |list|
      list.destroy
    end

    # Destroy all of the user's classbooks
    @user.classbooks.each do |classbook| 
      classbook.destroy
    end
    
    # Destroy all of the user's classrooms
    @user.teaching_classrooms.each do |classroom| 
      classroom.destroy
    end
    
    @user.destroy
    flash[:success] = "Your account was deleted."
    redirect_to signup_path
  end
  
  def admin
    @teachers = []
    @students = []
    User.all.each do |user|
      @teachers << user if user.teaching_classrooms.any?
      @students << user if user.attending_classrooms.any?
    end
  end
  
  def remove_all_books
    current_user.books.each do |book|
      book.destroy
    end
    flash[:success] = "Your books inside lists were successfully deleted."
    redirect_to edit_user_path(current_user)
  end
  
  def remove_all_classbooks
    current_user.classbooks.each do |classbook|
      classbook.destroy
    end
    flash[:success] = "Your books inside classrooms were successfully deleted."
    redirect_to edit_user_path(current_user)
  end
  
  def remove_all_lists
    current_user.lists.each do |list|
      list.destroy
    end
    flash[:success] = "Your lists were successfully deleted."
    redirect_to edit_user_path(current_user)
  end

  private
    def filter_admin
      unless current_user.admin == true
        raise_error(ActionController::RoutingError)
      end
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :remove_avatar, :bio, :lists_enabled, :profile_private)
    end

    # Before filters

    # Signup => Profile if logged in
    def logged_in_change_links
      unless not logged_in?
        redirect_to classrooms_path
      end
    end

    def authenticate
      authenticate_or_request_with_http_basic('Administration') do |code|
        code == 'best29cacti'
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def profile_private
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to(root_url) if @user.profile_private
      end
    end

    def check_if_user_exists
      unless logged_in?
        redirect_to root_url
      end
    end


end

app/helpers/users_helper.rb
module UsersHelper
  
  def avatar_for(user, options = { size: 80 })
    size = options[:size]
    if user.avatar?
      image_tag user.avatar.url, class: "avatar", height: size, width: size
    else
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=mm&s=#{size}"
      image_tag(gravatar_url, alt: user.name, class: "avatar", height: size, width: size)
    end
  end
end

app/views/users/edit.html.erb
<% provide(:title, "Settings") %>
<div class="container-fluid">
  <h1 class="h1-centered">Settings</h1>
  <!-- Form for editing user -->
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(current_user, html: { multipart: true }) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="row md-center">
          <div class="col-md-2">
            <div class="settings-avatar">
              <%= avatar_for current_user, size: 80 %>
            </div>
          </div>
          <div class="col-md-10">
            <%= f.label :change_your_avatar %>
            <%= f.file_field :avatar, accept: 'image/jpeg,image/gif,image/png', class:"form-control" %>
            <div style="margin-left:15px">
              <%= f.label :remove_avatar, class: "checkbox" do %>
                <%= f.check_box :remove_avatar %>
                <span>Remove avatar</span>
              <% end %>
            </div>
          </div>
          
          <!-- Save button -->
        <div class = "center bottom-medium-margins">
          <%= f.submit "Save avatar", class: "btn btn-default green-hover" %>
        </div>
        </div>
        <hr>
        <!-- Name -->
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <!-- Email -->
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        <!-- Bio -->
        <%= f.label :bio %>
        <%= f.text_area :bio, class: 'form-control', placeholder: "140 characters max." %>
        <hr>
        <!--Enable lists-->
        <%= f.label :lists %>
        <br>
        <span>Log books without having to join a classroom.</span>
        <%= f.label :enable_lists, class: "checkbox" do %>
          <%= f.check_box :lists_enabled %>
          <span>Enable lists</span>
        <% end %>
        <hr>
        <!--Enable lists-->
        <%= f.label :profile_page %>
        <br>
        <span>If checked, no one but you can view your profile page. Otherwise, anyone can view your profile page.</span>
        <%= f.label :profile_private, class: "checkbox" do %>
          <%= f.check_box :profile_private %>
          <span>Private profile page</span>
        <% end %>

        <hr>
        <!-- Password -->
        <%= f.label :new_password %>
        <%= f.password_field :password, class: 'form-control', placeholder: 'Optional' %>
        <!-- Password confirmation -->
        <%= f.label :new_password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder:'Confirm your new password' %>
        
        <!-- Save button -->
        <div class = "center bottom-medium-margins">
          <%= f.submit "Save changes", class: "btn btn-default green-hover" %>
        </div>
      <% end %>
      
      <hr>
      
      <% if current_user.lists.any? %>
        <%= link_to "Remove all lists", remove_all_lists_path(current_user), data: {confirm: "Are you sure you want to remove all your lists? This action cannot be undone."} %><br>
      <% end %>
      <% if current_user.books.any? %>
        <%= link_to "Remove all books inside lists", remove_all_books_path(current_user), data: {confirm: "Are you sure you want to remove all your books inside lists? This action cannot be undone."} %><br>
      <% end %>
      <% if current_user.classbooks.any? %>
        <%= link_to "Remove all books inside classrooms", remove_all_classbooks_path(current_user), data: {confirm: "Are you sure you want to remove all your books inside classrooms? This action cannot be undone."} %>
      <% end %>
      
      <hr>
      
      <div class="center">
        <h3 style="margin-top:30px; margin-bottom:15px">Delete your account</h3>
        <p class="center">This action can't be reversed, so make sure it's what you want.</p>
        <%= link_to(current_user, method: :delete, data: {confirm: "Are you sure you want to delete your account? This will permanently delete all your lists and books. This action can't be reversed."}) do %>
          <btn class="btn btn-danger">Delete your account</btn>
        <% end %>
      </div>

    </div>
  </div>
</div>


<script type="text/javascript">
  $('#avatar_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class = "container">
  <h1 class="h1-default">Sign up for a free account</h2>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.text_field :name, class: 'form-control', placeholder: 'Name', autofocus: 'autofocus' %>

        <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>

        <%= f.password_field :password, class: 'form-control', placeholder: 'Password (six characters minimum)' %>
        
        <%= f.password_field :password_confirmation, class: 'form-control bottom-medium-margins', placeholder: 'Confirm your password' %>
        
        <%= hidden_field_tag "new_user", true %>
        
        <!--<p class = "center bottom-small-margins">By clicking submit, you agree to the <%# link_to "Terms of Service", terms_path %> and <%# link_to "Privacy Policy.", privacy_path %></p>-->
        <div class="center">
          <%= f.submit "Create my account", class: "btn btn-default green-hover bottom-medium-margins" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="center">
    <span><%= link_to "Already have an account?", login_path %></span>
  </div>
</div>

<script>
	// Disable form after one click so that you can't add the book twice
  var $myForm = $("#new_user");
	$myForm.submit(function(){
	    $myForm.submit(function(){
	        return false;
	    });
	});

</script>

app/views/users/show.html.erb
<% if (not @user.profile_private) || @user == current_user%>
  <% provide(:title, @user.name) %>
  <div class="container" style="margin-top:30px">
    <div class="pull-right">
      <% if @user == current_user %>
  	    <%= link_to edit_user_path(current_user) do %>
          <i class="glyphicon glyphicon-pencil"></i>
            <span>Edit your profile</span>
          <% end %> 
        <% end %> 
      </div>
      <div class="center" style="margin:30px 30px">
        <%= avatar_for @user, size: 80 %>
        <h1><%= @user.name %></h1>
        <p><%= @user.bio %></p>
        <br>
        <p style="color:gray">Joined <%= time_ago_in_words(@user.created_at) %> ago</p>
        <br>
      </div>
      <div class="row">
          <div class="col-xs-6 col-sm-3 center">
            <h1><%= @books_count %></h1>
            <span>books read</span>
          </div>
          <div class="col-xs-6 col-sm-3 center">
            <h1><%= @page_count %></h1>
            <span>pages read</span>
          </div>
          <div class="col-xs-6 col-sm-3 center">
            <h1><%= @user.teaching_classrooms.count %></h1>
            <span>classrooms teaching</span>
          </div>
          <div class="col-xs-6 col-sm-3 center">
            <h1><%= @user.attending_classrooms.count %></h1>
            <span>classrooms joined</span>
          </div>
      </div>
      <hr>
      
      <% if @recent_books.any? %>
        <%= render @recent_books %> 
      <% else %>
        <% if @user == current_user %>
          <p class="center">You haven't added any books.</p>
        <% else %>
          <p class="center">This user hasn't added any books.</p>
        <% end %>
      <% end %>
  </div>
<% else %>
  <% provide(:title, "Profile not found.") %>
  <div class="container-fluid">
    <h1>Profile not found.</h1>
    <p class="center">This profile may be private. You may be able to view it by <%= link_to "logging in.", login_path %></p>
  </div>
<% end %>