config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get    'unlock_account'       => 'users#unlock_account'

  # Dynamic error pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # devise_for :users
  # Static pages
  root                      'static_pages#home'
  # get    'terms'         => 'static_pages#terms'
  # get	   'privacy'       => 'static_pages#privacy'
  # get    'about'         => 'static_pages#about'
  # get    'apps'          => 'static_pages#apps'
  # get    'changelog'     => 'static_pages#changelog'
  # get    'feedback'      => 'static_pages#feedback'
  get    'support'       => 'static_pages#support'

  # Sessions
  get	   'login'		     => 'sessions#new'
  post	 'login'		     => 'sessions#create'
  delete 'logout'	       => 'sessions#destroy'

  # Users
  # get    'profile'       => 'users#show'
  get    'signup'        => 'users#new'
  
  resources :users, only: [:new, :show, :create, :edit, :update, :destroy]
  
  # Destroy
  get  'users/:id/remove_all_books' => 'users#remove_all_books', as: :remove_all_books
  get  'users/:id/remove_all_classbooks' => 'users#remove_all_classbooks', as: :remove_all_classbooks
  get  'users/:id/remove_all_lists' => 'users#remove_all_lists', as: :remove_all_lists
  
  # Lists
  get    'import_page'        => 'lists#import_page'
  
  resources :lists
  
  # Books
  get    'search'        => 'books#search'
  
  resources :books
  resources :reviews, only: [:edit, :update]

  # Password Resets
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/new'
  get 'password_resets/edit'

  # Classrooms
  get    'classroom_join'      => 'classrooms#join'
  get    'classroom_activity'  => 'classrooms#activity'
  get    'student'             => 'classrooms#student'
  get    'leaderboards'        => 'classrooms#leaderboards'
  get    'students'            => 'classrooms#students'
  get    'archived'            => 'classrooms#archived'
  get    'info'                => 'classrooms#info'
  get    'leave_classroom'     => 'classrooms#leave'
  
  get  'classrooms/:id/remove' => 'classrooms#remove_student', as: :remove_student
  get  'classrooms/:id/remove_self' => 'classrooms#remove_self', as: :remove_self
  get  'classrooms/:id/archive' => 'classrooms#archive', as: :archive
  
  resources :classrooms
  resources :terms
  
  # Classbooks
  get    'classroomsearch'     => 'classbooks#search'
  get    'classbooks_print'    => 'classbooks#print'
  resources :classbooks
  
end

app/views/books_classbooks/_book_actions.html.erb
<span>
    <!--Edit review (non-manual) or edit book (manual)-->
    <% if book.manual %>
        <% if defined? book.term_id %>
            <%= link_to edit_classbook_path(book), class: "btn btn-default green-hover" do %>
                <span class="fa fa-edit"></span>
                <span>Edit book</span>
            <% end %>
        <% else %>
            <%= link_to edit_book_path(book), class: "btn btn-default green-hover" do %>
                <span class="fa fa-edit"></span>
                <span>Edit book</span>
            <% end %>
        <% end %>
    <% else %>
        <% if @review %>
            <%= link_to edit_review_path(@review), class: "btn btn-default green-hover" do %>
                <span class="fa fa-edit"></span>
                <span>Edit review</span>
            <% end %>
        <% else %>
            <% if defined? book.term_id %>
                <%= link_to edit_classbook_path(book), class: "btn btn-default green-hover" do %>
                    <span class="fa fa-edit"></span>
                    <span>Edit review</span>
                <% end %>
            <% else %>
                <%= link_to edit_book_path(book), class: "btn btn-default green-hover" do %>
                    <span class="fa fa-edit"></span>
                    <span>Edit review</span>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
</span>
<!--Delete book button-->
<span style="margin-left:20px">
    <%= link_to(book, method: :delete, class: "btn btn-default green-hover") do %>
    	<span class="fa fa-trash"></span>
    	<span>Remove book</span>
    <% end %>
</span>

app/views/books_classbooks/_book_image.html.erb
<!--Book image or manual thumbnail-->
<% unless book.manual %>
  <% book_url = book.amazon_url ? book.amazon_url : book.image_url %>  

  <!--Link to amazon url from book-->
	<%= link_to image_tag(book.image_url, class: "center", width: "150", height: "auto", alt: book.title), book_url %><br><br>
<% end %>

app/views/books_classbooks/_book_review.erb
<!--Show editorial review if there is one, also hide the full content with a show more if needed-->
<% unless book.manual %>
    <% if book.description  %>
        <h4>Description:</h4>
        <!--Display the editorial review-->
    	<p><%= sanitize book.description, tags: %w(br p) %></p>
        <hr>
    <% end %>
<% end %>
<!--Show current_user's review-->
<h4>Your review:</h4>
<% if book.review && (not book.review.blank?) %>
    <p><%= sanitize @markdown.render(book.review)%></p>
<% else %>
    <p><i>You haven't written a review.</i></p>
<% end %>

<!--Show other people's reviews-->
<%# if @reviews && @reviews.any? %>
    <%# render 'books_classbooks/review_table' %>
<%# end %>

app/views/books_classbooks/_review_table.html.erb
<hr>
<h4 style="margin-bottom:30px">Other users' reviews:</h4>
<table class="table">
    <col width="20%">
    <col width="80%">
    <% if @reviews %>
        <!--Go through each review and display user and content-->
        <% @reviews.each do |review| %>
            <tr>
                <!--Find user-->
                <% @user = User.find_by(id: review.user_id) %>
                <td class="center">
                    <!--Display avatar-->
                	<%= avatar_for @user, size: 50 %>
                	<br>
                	<!--Display user name-->
                	<p style="margin-top:15px"><%= @user.name %></p>
                </td>
                <td>
                    <div class="show-more-text">
                		<p><%= sanitize @markdown.render(review.content) %></p>
                	</div>
                </td>
            </tr>
        <% end %>
    <% end %>
</table>