config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get    'unlock_account'       => 'users#unlock_account'

  # Dynamic error pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # devise_for :users
  # Static pages
  root                      'static_pages#home'
  # get    'terms'         => 'static_pages#terms'
  # get	   'privacy'       => 'static_pages#privacy'
  # get    'about'         => 'static_pages#about'
  # get    'apps'          => 'static_pages#apps'
  # get    'changelog'     => 'static_pages#changelog'
  # get    'feedback'      => 'static_pages#feedback'
  get    'support'       => 'static_pages#support'

  # Sessions
  get	   'login'		     => 'sessions#new'
  post	 'login'		     => 'sessions#create'
  delete 'logout'	       => 'sessions#destroy'

  # Users
  # get    'profile'       => 'users#show'
  get    'signup'        => 'users#new'
  
  resources :users, only: [:new, :show, :create, :edit, :update, :destroy]
  
  # Destroy
  get  'users/:id/remove_all_books' => 'users#remove_all_books', as: :remove_all_books
  get  'users/:id/remove_all_classbooks' => 'users#remove_all_classbooks', as: :remove_all_classbooks
  get  'users/:id/remove_all_lists' => 'users#remove_all_lists', as: :remove_all_lists
  
  # Lists
  get    'import_page'        => 'lists#import_page'
  
  resources :lists
  
  # Books
  get    'search'        => 'books#search'
  
  resources :books
  resources :reviews, only: [:edit, :update]

  # Password Resets
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/new'
  get 'password_resets/edit'

  # Classrooms
  get    'classroom_join'      => 'classrooms#join'
  get    'classroom_activity'  => 'classrooms#activity'
  get    'student'             => 'classrooms#student'
  get    'leaderboards'        => 'classrooms#leaderboards'
  get    'students'            => 'classrooms#students'
  get    'archived'            => 'classrooms#archived'
  get    'info'                => 'classrooms#info'
  get    'leave_classroom'     => 'classrooms#leave'
  
  get  'classrooms/:id/remove' => 'classrooms#remove_student', as: :remove_student
  get  'classrooms/:id/remove_self' => 'classrooms#remove_self', as: :remove_self
  get  'classrooms/:id/archive' => 'classrooms#archive', as: :archive
  
  resources :classrooms
  resources :terms
  
  # Classbooks
  get    'classroomsearch'     => 'classbooks#search'
  get    'classbooks_print'    => 'classbooks#print'
  resources :classbooks
  
end

app/views/layouts/_dropdown.html.erb
<!-- DROPDOWN -->
<span class="btn-group dropdown hidden-xs pull-right">
  <!-- Dropdown toggle -->
  <button class= "btn dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="padding-top: 0px" align="right">
    <!-- Avatar -->
    <%= avatar_for current_user, size: 30 %>
    <!-- Caret -->
    <span class="caret" style="color:white"></span>
  </button> <!-- End dropdown toggle -->
  <!-- Dropdown menu -->
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <!-- Settings -->
    <li class="dropdown-li"><%= link_to "Profile", user_path(current_user) %></li>
    <!--<li class="dropdown-li"><%# link_to 'Badges', badges_path %><li>-->
    <li class="dropdown-li"><%= link_to "Settings", edit_user_path(current_user) %></li>
    <!-- Separator -->
    <li role="separator" class="divider"></li>
    <!-- Log out -->
    <li class="dropdown-li"> <%= link_to "Log out", logout_path, method: "delete" %> </li>
  </ul> <!-- End dropdown menu -->
</span> <!-- END DROPDOWN -->

app/views/layouts/_footer.html.erb
<!--Font awesome-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

<% if @home %>
<footer class="footer-home">
	<p><%= link_to support_path do %><i class="fa fa-question-circle"></i><span>Support</span><% end %></p>
	<p>(c) <%= Time.now.year %> Readlio. All rights reserved.</p>
</footer>
<% else %>
<footer class="footer-sm">
	<hr>
	<ul>
		<li><%= link_to support_path do %><i class="fa fa-question-circle"></i><span>Support</span><% end %></li>
		<span class="pull-right hidden-xs">(c) <%= Time.now.year %> Readlio. All rights reserved.</span>
	</ul>
</footer>
<% end %>

app/views/layouts/_head.html.erb
<!-- Make responsive -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
<!--SEO Keywords-->
<meta name="keywords" content="books,reading,log,school,english,lists,amazon,classroom,pages,suggestions,recommendations,classmates,count,page,student,teacher,reviews,recording,form">
<!--Favicon-->
<%= render 'favicon' %>

<!-- Validation for Bing webmaster tools -->
<meta name="msvalidate.01" content="4A53A59FC482B28E5AB468A83F0F9947" />

<!--Verification for readlio.com-->
<meta name="google-site-verification" content="b1TqYfseJGAaXMdqnFAWDtlWKtgEspLFZxhjNS4AxbY" />

<!--Verification for www.readlio.com-->
<meta name="google-site-verification" content="b1TqYfseJGAaXMdqnFAWDtlWKtgEspLFZxhjNS4AxbY" />

<!--Script to include Google Analytics-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75863150-1', 'auto');
  ga('send', 'pageview');

</script>

<!--Include stylesheets-->
<%= stylesheet_link_tag 'application', media: 'all', "data-turbolinks-track" => true %>
<%# stylesheet_link_tag('print', :media => :print) %>
<%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

<title><%= full_title(yield(:title)) %></title>

app/views/layouts/_home_nav.erb
<nav class="navbar navbar-home navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <!-- Nav collapse (only for mobile) -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <!-- Logo -->
        <%# image_tag 'logo.png', class: "logo-img" %>
        <a class="navbar-title"><%= link_to "Readlio", root_path, id: "logo" %></a>
      </div>
      <!-- Start nav collapse (right hand side)-->
      <div class="collapse navbar-collapse navbar-normal" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <!-- Appear if not logged in -->
          <li><%= link_to "Log in",  login_path %></li>
          <li><%= link_to "Sign up",   signup_path %></li>
        </ul> <!-- End navbar unordered list -->
      </div> <!-- End nav collapse (right hand side)-->
    </div>
  </nav>

app/views/layouts/_nav.html.erb
<% unless @home %>
  <nav class="navbar navbar-normal navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <!-- Nav collapse (only for mobile) -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <!-- Logo -->
        <a class="navbar-title"><%= link_to "Readlio", root_path, id: "logo" %></a>
      </div>

      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
              <!--Classrooms-->
              <li id="classrooms-li"><%= link_to "Classrooms", classrooms_path %></li>
              <!--Lists - only if enabled-->
              <% if current_user.lists_enabled %>
                <li id="lists-li"><%= link_to "Lists", lists_path %></li>
              <% end %>
              <% if current_user.admin %>
                <li><%= link_to "Admin", '/admin', :"data-no-turbolink" => true %></li>
              <% end %>
              <li></li>
            <!-- Mobile links -->
            <li class="visible-xs"><%= link_to "Profile", user_path(current_user) %></li>
            <li class="visible-xs"><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="visible-xs"> <%= link_to "Log out", logout_path, method: "delete" %> </li>
            <%= render 'layouts/dropdown' %>
          <% else %>
            <!-- Appear if not logged in -->
            <li><%= link_to "Log in",  login_path %></li>
            <li><%= link_to "Sign up",   signup_path %></li>
          <% end %> <!-- End if logged in -->
        </ul> <!-- End navbar unordered list -->
      </div> <!-- End nav collapse (right hand side)-->
    </div> <!-- End container-fluid -->
  </nav>
<% else %>
  <%= render 'layouts/home_nav' %>
<% end %>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
         <%= yield(:side_bar) %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <% if content_for(:side_bar) %>
      <div id="wrapper">
        <%= render 'layouts/sidebar' %>
        <div id="page-content-wrapper">
    <% end %>
        <% flash.each do |message_type, message| %>
          <%= content_tag :div, class: "alert alert-#{message_type} alert-dismissable" do %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= message %>
          <% end %>
        <% end %>
        <% if logged_in? %>
          <%= render 'shared/ad_banner' %>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
      <% if content_for(:side_bar) %>
      </div>
      </div>
      <% end %>
  </body>
  
</html>